import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navber";
import Session from "./Session";
import ProviderStore from "./Provider";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={false}>
      <ProviderStore>
        <Session>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
          >
            <Navbar />
            <main className="w-full min-h-[100vh] overflow-x-auto text-zinc-800 hide-scrollbar">
              {children}
            </main>
            <Footer />
          </body>
        </Session>
      </ProviderStore>
    </html>
  );
}
